CREATE TABLE IF NOT EXISTS movie (
    id SERIAL PRIMARY KEY,
    title VARCHAR(50) NOT NULL,
    description VARCHAR(100) NOT NULL,
    releasedate DATE NOT NULL,
    genre TEXT[] NOT NULL 
);

CREATE TABLE IF NOT EXISTS genre (
    name VARCHAR(50) PRIMARY KEY
);